from telepot.namedtuple import (
    ReplyKeyboardMarkup, 
    KeyboardButton,
    InlineKeyboardMarkup,
    InlineKeyboardButton
)

from bot import write,write_location

def show_type_selection(data = None,session = None):
    """
    Show a message with keyboard to choose the desired shop type.
    data (dict): Data dict generated by read functions in bot.py
    session (dict): A dict representin the session or None if no session has been created

    return: message (dict, telegram message object https://core.telegram.org/bots/api#message) 
    """

    replyKeyboard = InlineKeyboardMarkup(inline_keyboard=[
        [InlineKeyboardButton(text="🍞 麵包店",callback_data="type0")],
        [InlineKeyboardButton(text="☕️ 咖啡廳",callback_data="type1")],
        [InlineKeyboardButton(text="🍛 餐廳",callback_data="type2")],
        [InlineKeyboardButton(text="🍺 酒吧",callback_data="type3")],
    ])

    return write(data=data,msg="要選擇什麼類型的食物呢？",keyboard=replyKeyboard,session=session)

def show_stores(session):
    """
    Show a message with keyboard to choose the desire store.

    session (dict): A dict representin the session

    return: message (dict, telegram message object https://core.telegram.org/bots/api#message)
    """

    inline_keyboard = []
    for i,restaurant in enumerate(session["result_list"]):
        inline_keyboard.append([InlineKeyboardButton(text="✔️" +  restaurant['name'] +  "\n (" +  str(restaurant['dis']) +  "m)", callback_data="store" + str(i))])
    inline_keyboard.append([InlineKeyboardButton(text="⤴️上一頁",callback_data="return_to_type")])

    replyKeyboard = InlineKeyboardMarkup(inline_keyboard=inline_keyboard)

    return write(data = None, msg = "以下為距離您最近的 {} 家店家：".format(len(session["result_list"])), keyboard = replyKeyboard,session = session)


def show_store_detail(session, index, with_keyboard = True):
    
    replyKeyboard = InlineKeyboardMarkup(inline_keyboard=[
        [InlineKeyboardButton(text="⤴️上一頁",callback_data="return_to_stores")],
        [InlineKeyboardButton(text="👌OK",callback_data="OK" + str(index))]
    ])
    store = session["result_list"][index]

    return write(data = None, msg = "以下為此店家的相關資訊：\n"
				"🏠 店名：" + store['name'] +  "\n"
				"📞 電話：" + store['tel'] + "\n"
                "🚲 距離：" + str(store['dis']) + "m\n"
                "📝 地址：" + store['add'] + "\n"
                "📊 評等：" + "⭐" * store["rating_rounded"] + store["rating_string"] + "\n"
                "⏰ 營業：" + store["open"] + "\n"
                ,keyboard = replyKeyboard if with_keyboard else None,session = session)    